Add sale defpact; add sale and transfer policy
kadena-io/hft pull request #11
Opened 2021-11-11 01:50 UTC by sirlensalot

2021-11-12 22:03 UTC, sirlensalot commented on pact/hft.pact
> +    @doc "Initiate sale with by SELLER by escrowing AMOUNT of TOKEN until TIMEOUT."
```suggestion
    @doc "Initiate sale with by SELLER by escrowing AMOUNT of TOKEN."
```

2021-11-12 22:09 UTC, sirlensalot commented on pact/hft.pact
> +    @doc "Withdraw offer by SELLER of AMOUNT of TOKEN before TIMEOUT"
```suggestion
    @doc "Withdraw offer by SELLER of AMOUNT of TOKEN "
```

2021-11-12 22:15 UTC, sirlensalot commented on pact/hft.pact
> +    (emit-event (TRANSFER token seller buyer amount))
Should probably emit transfer for all steps.

2021-11-16 16:18 UTC, ggobugi27 commented on pact/fixed-quote-policy.pact
> +  )
```suggestion
  (defun enforce-mint:bool
    ( token:object{token-info}
      account:string
      amount:decimal
    )
    (bind (get-policy token)
      { 'mint-guard:=mint-guard:guard
      , 'max-supply:=max-supply:decimal
      }
      (enforce-guard (at 'mint-guard (get-policy token)))
      (enforce (<= (+ amount (at 'supply token)) max-supply))
      )
  )
 ```

2021-11-17 20:38 UTC, ggobugi27 requested changes

2021-11-17 20:38 UTC, ggobugi27 commented on pact/hft.pact
> +        (offer token seller amount timeout))
`offer` function has no argument for `timeout`

2021-11-17 20:38 UTC, ggobugi27 commented on pact/hft.pact
> +    (debit token seller amount)
Looks like the capability `DEBIT` is not granted to this function. I also tried adding `(with-capability (OFFER ..))` to wrap around `debit` and `credit` but still doesn't resolve.

2021-11-23 16:55 UTC, ggobugi27 approved these changes
Looks good to me.

2021-11-23 17:03 UTC, merged